image: node:alpine

before_script:
  - yarn install

test (NodeJS latest): &test-definition
  stage: test
  script:
    - npm test
  tags:
    - docker

test (NodeJS 10):
  image: node:10-alpine
  <<: *test-definition

test (NodeJS 8):
  image: node:8-alpine
  <<: *test-definition

test (NodeJS 6):
  image: node:6-alpine
  <<: *test-definition
