image: node:alpine

before_script:
  - yarn install

test (NodeJS latest): &test-definition
  stage: test
  script:
    - yarn test
  tags:
    - docker

test (NodeJS 20):
  image: node:20-alpine
  <<: *test-definition

test (NodeJS 18):
  image: node:18-alpine
  <<: *test-definition

test (NodeJS 16):
  image: node:16-alpine
  <<: *test-definition
